config/routes.rb
Rails.application.routes.draw do
  get 'hello' => 'greetings#hello'
  get 'bye' => 'greetings#bye'
  get 'course_tables/index' => 'course_tables#index'
  resources :course_tables
  resources :greetings
  root :to => 'greetings#hello'

end

app/models/course_table.rb
class CourseTable < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/course_tables_controller.rb
class CourseTablesController < ApplicationController
  before_action :set_course_table, only: [:show, :edit, :update, :destroy]

  # GET /course_tables
  # GET /course_tables.json
  def index
    @course_tables = CourseTable.all
  end

  # GET /course_tables/1
  # GET /course_tables/1.json
  def show
  end

  # GET /course_tables/new
  def new
    @course_table = CourseTable.new
  end

  # GET /course_tables/1/edit
  def edit
  end

  # POST /course_tables
  # POST /course_tables.json
  def create
    @course_table = CourseTable.new(course_table_params)

    respond_to do |format|
      if @course_table.save
        format.html { redirect_to @course_table, notice: 'Course table was successfully created.' }
        format.json { render :show, status: :created, location: @course_table }
      else
        format.html { render :new }
        format.json { render json: @course_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_tables/1
  # PATCH/PUT /course_tables/1.json
  def update
    respond_to do |format|
      if @course_table.update(course_table_params)
        format.html { redirect_to @course_table, notice: 'Course table was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_table }
      else
        format.html { render :edit }
        format.json { render json: @course_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_tables/1
  # DELETE /course_tables/1.json
  def destroy
    @course_table.destroy
    respond_to do |format|
      format.html { redirect_to course_tables_url, notice: 'Course table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_table
      @course_table = CourseTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_table_params
      params.require(:course_table).permit(:coursename, :teachername, :coursenum, :courseroom, :avaliablenums)
    end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello

	@time_now
	@greeting

	tody=Time.new
	@time_hours=tody.hour

	if @time_hours < 4  then @greeting ="夜深了，早点休息吧！"	
	else if @time_hours < 11 then @greeting ="早上好，充实的一天开始了：）"
	else if @time_hours < 19 then @gteeting ="下午好，更加努力的工作吧！"	
	else @greeting = "晚上好，下班回家多陪陪家人吧～"
	end 
	@time_now = "当前时间："+tody.strftime("%Y-%m-%d %H:%M:%S")
	end
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_tables_helper.rb
module CourseTablesHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/course_tables/_form.html.erb
<%= form_for(@course_table) do |f| %>
  <% if @course_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_table.errors.count, "error") %> prohibited this course_table from being saved:</h2>

      <ul>
      <% @course_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coursename %><br>
    <%= f.text_field :coursename %>
  </div>
  <div class="field">
    <%= f.label :teachername %><br>
    <%= f.text_field :teachername %>
  </div>
  <div class="field">
    <%= f.label :coursenum %><br>
    <%= f.number_field :coursenum %>
  </div>
  <div class="field">
    <%= f.label :courseroom %><br>
    <%= f.text_field :courseroom %>
  </div>
  <div class="field">
    <%= f.label :avaliablenums %><br>
    <%= f.number_field :avaliablenums %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_tables/edit.html.erb
<h1>Editing Course Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_table %> |
<%= link_to 'Back', course_tables_path %>

app/views/course_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Course Tables</h1>

<table>
  <thead>
    <tr>
      <th>Coursename</th>
      <th>Teachername</th>
      <th>Coursenum</th>
      <th>Courseroom</th>
      <th>Avaliablenums</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_tables.each do |course_table| %>
      <tr>
        <td><%= course_table.coursename %></td>
        <td><%= course_table.teachername %></td>
        <td><%= course_table.coursenum %></td>
        <td><%= course_table.courseroom %></td>
        <td><%= course_table.avaliablenums %></td>
        <td><%= link_to 'Show', course_table %></td>
        <td><%= link_to 'Edit', edit_course_table_path(course_table) %></td>
        <td><%= link_to 'Destroy', course_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course table', new_course_table_path %>
<h3><a href="hello.html">back to home</h3>

app/views/course_tables/new.html.erb
<h1>New Course Table</h1>

<%= render 'form' %>

<%= link_to 'Back', course_tables_path %>

app/views/course_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coursename:</strong>
  <%= @course_table.coursename %>
</p>

<p>
  <strong>Teachername:</strong>
  <%= @course_table.teachername %>
</p>

<p>
  <strong>Coursenum:</strong>
  <%= @course_table.coursenum %>
</p>

<p>
  <strong>Courseroom:</strong>
  <%= @course_table.courseroom %>
</p>

<p>
  <strong>Avaliablenums:</strong>
  <%= @course_table.avaliablenums %>
</p>

<%= link_to 'Edit', edit_course_table_path(@course_table) %> |
<%= link_to 'Back', course_tables_path %>

app/views/greetings/bye.html.erb
<h1>See you again~</h1>
<h1><a href="hello.html">If you want to get back,click here!</a></h1>

app/views/greetings/hello.html.erb
<div class="container">
	<div class="row">
	  <div class="col-md-8" style="background-color: #18BC9C;padding-bottom: 10px;padding-top: 10px">
		<div style="font-size: 50px;padding-left: 50px">
			<%=image_tag "profile.png"%>
			<%= @greeting %>
		</div>
	</div>	
</div>
<p><%= @time_now %></p>
<h1><a href="course_tables.html">Show CourseSelect Tables</a></h1>
<h1><a href="http://www.ucas.ac.cn">click here to UCAS</a></h2>
<h1><a href="bye.html">Bye~bye</a></h3>
<p><%=@time_noww%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hellorailapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>